<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Klevu\FrontendSearch\ViewModel\Html\Head\SearchBoxTarget;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

// phpcs:disable SlevomatCodingStandard.Commenting.InlineDocCommentDeclaration.MissingVariable
/**
 * @var SecureHtmlRenderer $secureRenderer
 * @var ViewModelRegistry $viewModels
 * @var SearchBoxTarget $klevuSearchBoxTarget
 */
// phpcs:enable SlevomatCodingStandard.Commenting.InlineDocCommentDeclaration.MissingVariable
$klevuSearchBoxTarget = $viewModels->require(SearchBoxTarget::class);
$klevuSearchBoxTargetId = $klevuSearchBoxTarget->getSearchBoxTargetId();
?>

<?php if ($klevuSearchBoxTargetId): ?>
    <?php
    $scriptString = "

    klevu.interactive(function () {
        const searchBoxTarget = document.getElementById('$klevuSearchBoxTargetId');
        if ('undefined' !== typeof searchBoxTarget && searchBoxTarget) {
            let options = {};
            klevu.setObjectPath(options, 'search.searchBoxTarget', searchBoxTarget);
            klevu(options);
        }
    });
    ";
    ?>

    <?= $secureRenderer->renderTag(
        tagName: 'script',
        attributes: ['type' => 'text/javascript'],
        content: $scriptString,
        textContent: false,
    ) ?>

<?php endif ;?>
