<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Klevu\FrontendSearch\ViewModel\Html\Head\SearchBoxTarget;
use Klevu\FrontendSearch\ViewModel\Html\Head\SearchForm;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Magento\Search\Helper\Data as SearchHelper;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper

/** @var Escaper $escaper */
/** @var Template $block */
/** @var SearchHelper $helper */

$helper = $this->helper(SearchHelper::class);

/** KLEVU CUSTOMISATION START */
/**
 * @var ViewModelRegistry $viewModels
 * @var SearchForm $klevuSearchForm
 * @var SearchBoxTarget $klevuSearchBoxTarget
 */
$klevuSearchForm = $viewModels->require(SearchForm::class);
$klevuQuickSearchEnabled = (bool)$klevuSearchForm->isKlevuQuickSearchEnabled();
$klevuSearchBoxTarget = $viewModels->require(SearchBoxTarget::class);
$klevuSearchBoxTargetId = $klevuSearchBoxTarget->getSearchBoxTargetId();
/** KLEVU CUSTOMISATION END */

?>
<script>
    'use strict';

    function initMiniSearch() {
        return {
            minSearchLength: <?= (int) $helper->getMinQueryLength() ?>,
            suggestions: [],
            suggest() {
                const search = this.$refs.searchInput;
                if (search.value.length >= this.minSearchLength) {
                    search.setCustomValidity('');
                    search.reportValidity();
                    this.fetchSuggestions(search.value);
                } else {
                    this.suggestions = [];
                }
            },
            fetchSuggestions(term) {
                fetch(
                    window.BASE_URL + 'search/ajax/suggest?' + new URLSearchParams({q: term}),
                    {
                        headers: {
                            'X-Requested-With': 'XMLHttpRequest'
                        }
                    }
                )
                    .then(response => response.json())
                    .then(result => this.suggestions = result);
            },
            search(term) {
                <?php /**
                 * KLEVU CUSTOMISATION START
                 * Add prevent (removed from form @submit.prevent="search()") when Klevu quicksearch disabled.
                 */ ?>
                <?php if (!$klevuQuickSearchEnabled): ?>
                    this.$refs.form.preventDefault();
                <?php endif; ?>
                <?php /** KLEVU CUSTOMISATION END */ ?>

                const search = this.$refs.searchInput;
                term = term || search.value;
                if (term.length < this.minSearchLength) {
                    search.setCustomValidity('<?= $escaper->escapeJs(
                        __('Minimum Search query length is %1', $helper->getMinQueryLength())
                    ) ?>');
                    search.reportValidity();
                } else {
                    search.setCustomValidity('');
                    search.value = term;
                    <?php /**
                     * KLEVU CUSTOMISATION START
                     * Skip form submit and let Klevu JS handle it.
                     * This is required for Klevu redirects.
                     */ ?>
                    <?php if (!$klevuQuickSearchEnabled): ?>
                        this.$refs.form.submit();
                    <?php endif; ?>
                    <?php /** KLEVU CUSTOMISATION END */ ?>

                }
            },
            focusElement(element) {
                if (element && element.nodeName === "DIV") {
                    element.focus();
                    return true;
                } else {
                    return false;
                }
            }
        }
    }
</script>
<div class="container py-2 mx-auto text-black" x-data="initMiniSearch()">
    <?php /**
     * KLEVU CUSTOMISATION START
     * Remove prevent from @submit.prevent="search()"
     * */ ?>
    <form class="form minisearch" id="search_mini_form" x-ref="form" @submit="search()"
          action="<?= $escaper->escapeUrl($helper->getResultUrl()) ?>" method="get">
        <?php /** KLEVU CUSTOMISATION END */ ?>
        <label class="hidden" for="search" data-role="minisearch-label">
            <span><?= $escaper->escapeHtml(__('Search')) ?></span>
        </label>
        <input id="search"
               x-ref="searchInput"
               type="search"
               autocomplete="off"
               name="<?= $escaper->escapeHtmlAttr($helper->getQueryParamName()) ?>"
               value="<?= /** @noEscape */ $helper->getEscapedQueryText() ?>"
               placeholder="<?= $escaper->escapeHtmlAttr(__('Search entire store here...')) ?>"
               maxlength="<?= $escaper->escapeHtmlAttr($helper->getMaxQueryLength()) ?>"
               class="w-full p-2 text-lg leading-normal transition appearance-none text-grey-800
                focus:outline-none focus:border-transparent lg:text-xl"
               @focus.once="suggest"
               @input.debounce.300="suggest"
               @keydown.arrow-down.prevent="focusElement($root.querySelector('[tabindex]'))"
        />
        <template x-if="suggestions.length > 0">
            <div class="w-full leading-normal transition appearance-none text-grey-800 flex flex-col mt-1">
                <template x-for="suggestion in suggestions">
                    <div class="flex justify-between p-2 bg-container-lighter even:bg-container mb-1 cursor-pointer
                                 border border-container hover:bg-container-darker"
                         tabindex="0"
                         @click="search(suggestion.title)"
                         @keydown.enter="search(suggestion.title)"
                         @keydown.arrow-up.prevent="
                              focusElement($event.target.previousElementSibling) || $refs.searchInput.focus()
                          "
                         @keydown.arrow-down.prevent="focusElement($event.target.nextElementSibling)"
                    >
                        <span x-text="suggestion.title"></span>
                        <span x-text="suggestion.num_results"></span>
                    </div>
                </template>
            </div>
        </template>
        <button type="submit"
                title="<?= $escaper->escapeHtml(__('Search')) ?>"
                class="action search sr-only"
                aria-label="Search"
        >
            <?= $escaper->escapeHtml(__('Search')) ?>
        </button>
    </form>
</div>

<?php if ($klevuQuickSearchEnabled): ?>
    <?php /**
     * KLEVU CUSTOMISATION START
     * Add search results box
     * Prevents search box disappearing while Klevu results are displaying
     */ ?>
    <div id="<?= $escaper->escapeHtmlAttr($klevuSearchBoxTargetId . "_wrapper") ?>"
         class="<?= $escaper->escapeHtmlAttr($klevuSearchBoxTargetId . "_wrapper") ?>">
        <div id="<?= $escaper->escapeHtmlAttr($klevuSearchBoxTargetId) ?>"
             class="<?= $escaper->escapeHtmlAttr($klevuSearchBoxTargetId) ?>"></div>
    </div>
    <style>
        <?= '#' . $escaper->escapeHtmlAttr($klevuSearchBoxTargetId) ?>.kuQuickSearchFacetedLayout>div {
            max-width: none !important;
        }
    </style>
<?php endif; ?>
<?php /** KLEVU CUSTOMISATION END */ ?>
